# This file is covered by the LICENSE file in the root of this project.
name: "industrial"
labels:
  0: "background"
  10: "unlabeled"
  50: "stairs"
  100: "chimney"
  150: "tanks"


color_map: # bgr
  0: [0,0,0]
  10: [0, 255, 0]
  50: [0, 0, 255]
  100: [255, 0, 0]
  150: [125,125,125]
  # 252: [245, 150, 100]

content: # as a ratio with the total number of points
  10: 0.25
  50: 0.25
  100: 0.25
  150: 0.25


# classes that are indistinguishable from single scan or inconsistent in
# ground truth are mapped to their closest equivalent
learning_map:
  0: 0
  10: 1     # "unlabeled"
  50: 2
  100: 3
  150: 4

learning_map_inv: # inverse of previous map
  0: 0      # "unlabeled", and others ignored
  1: 10
  2: 50
  3: 100
  4: 150
learning_ignore: # Ignore classes
  0: True
  1: False
  2: False
  3: False
  4: False

split: # sequence numbers
  train:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 9
    - 10
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
    - 27
    - 29
    - 30
    - 31
    - 32
    - 33
    - 34
    - 35
    - 36
    - 37
    - 39
    - 40
    - 41
    - 42
    - 43
    - 44
    - 45
    - 46
    - 47
    - 49
    - 50
    - 51
    - 52
    - 53
    - 54
    - 56
    - 57
    - 59
    - 60
    - 61
    - 62
    - 63
    - 64
    # - 65
    - 66
    - 67
    - 69
    - 70
    - 71
    - 72
    - 73
    - 74
    - 76
    - 77
    - 79
    - 80
    - 81
    - 82
    - 83
    - 84
    - 85
    - 86
    - 87
    - 89
    - 90
    - 91
    - 92
    - 93
    - 94
    - 95
    - 96
    - 97
    - 99
    - 100
    - 101
    - 102
    - 103
    - 104
    - 105
    - 106
    - 107
    - 109
    - 100
    - 101
    - 102
    - 103
    - 104
    - 105
    - 106
    - 107
    - 109
    - 110
    - 111
    - 112
    - 113
    - 114
    - 115
    - 116
    - 117
    - 119
    - 120
    - 121
    - 122
    - 123
    - 124
    - 125
    - 126
    - 128
    - 129
    - 140
    - 141
    - 142
    - 143
    - 144
    - 145
    - 146
    - 147
    - 149
    - 150
    - 151
    - 152
    - 153
    - 154
    - 156
    - 157
    - 158
    - 159
    - 160
# tanks
    - 170
    - 171
    - 172
    - 173
    - 174
    - 176
    - 177
    - 179
    - 180
    - 181
    - 182
    - 183
    - 184
    - 186
    - 188
    - 189
    - 190
    - 191
    - 193
    - 194
    - 195
    - 196
    - 197
    - 199
    - 200
    - 202
    - 203
    - 204
    - 206
    - 207
    - 208
    - 209
    - 210
    - 211
    - 212
    - 213
    - 214
    - 216
    - 218
    - 219
    - 220
    - 222
    - 223
    - 224
    - 226
    - 227
    - 228
    - 229



  valid:
    - 8
    - 55
    - 75
    - 127
    - 138
    - 155
    - 192
    - 221
    - 175


  test:
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 130
    - 131
    - 132
    - 133
    - 134
    - 135
    - 136
    - 137
    - 139
    - 187
    - 217
    - 201


    #160-229
